spring.application.name=compass-bank

# Threads virtuais (Java 21 - Project Loom)
spring.threads.virtual.enabled=true

# DataSource - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/compassbank
spring.datasource.username=compassbank
spring.datasource.password=compassbank
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logging
logging.level.org.cordeirops.compassbank=INFO
logging.level.org.springframework.kafka=WARN
